# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Notes for "The Bitcoin Book"
email: hilalh@noreply.github.com
description: This is a set of notes for "The Bitcoin Book" please look at the README.md file for more info.
  #  >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/bitcoinbook-notes" # the subpath of your site, e.g. /blog
url: "hilalh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hhgotit
github_username:  hilalh
repourl: 'https://github.com/hilalh/bitcoinbook-notes/tree/HEAD'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
